"""Rung commands for live editing.

Program listing, preview, and reverse-path (pyrung -> ladder) operations.
Reads from the persisted pyrung_project/ directory generated by AnalysisService.
"""

from __future__ import annotations

import difflib
import re
import sys
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .dispatch import DispatchContext


def _get_project_dir(ctx: DispatchContext) -> Path:
    """Get the persisted pyrung_project directory, or raise."""
    analysis = ctx.analysis
    if analysis is None or not analysis.is_available:
        raise ValueError("analysis not available (no Click project connected or build pending)")
    project_dir = analysis.project_dir
    if project_dir is None or not project_dir.is_dir():
        raise ValueError("pyrung project not persisted to disk yet")
    return project_dir


def _resolve_file(project_dir: Path, file_stem: str) -> Path:
    """Resolve a file stem (e.g. 'main', 'startup') to a .py path in the project."""
    if file_stem == "main":
        path = project_dir / "main.py"
    else:
        path = project_dir / "subroutines" / f"{file_stem}.py"
    if not path.is_file():
        raise ValueError(f"file not found: {path}")
    return path


def _all_file_stems(project_dir: Path) -> list[str]:
    """Return all file stems: main + sorted subroutines."""
    stems = ["main"]
    sub_dir = project_dir / "subroutines"
    if sub_dir.is_dir():
        stems.extend(p.stem for p in sorted(sub_dir.glob("*.py")))
    return stems


def _get_before_files(project_dir: Path) -> dict[str, str]:
    """Generate the 'before' state by round-tripping ladder CSVs through pyrung."""
    from pyrung.click import ladder_to_pyrung_project

    csv_dir = project_dir / "csv"
    if not csv_dir.is_dir():
        from ..ladder.program import program_save

        scr_folder = project_dir.parent
        csv_dir.mkdir(parents=True, exist_ok=True)
        program_save(scr_folder, csv_dir, index=True)

    nickname_csv = csv_dir / "nicknames.csv" if (csv_dir / "nicknames.csv").exists() else None
    return ladder_to_pyrung_project(csv_dir, nickname_csv=nickname_csv, index=True)


def _parse_rung_selection(selection: str) -> list[int]:
    """Parse rung selection: r3, r1..5, r3,r7 -> list of 1-based rung numbers."""
    parts = selection.upper().replace("R", "").split(",")
    rungs: list[int] = []
    for part in parts:
        part = part.strip()
        if ".." in part:
            lo, hi = part.split("..", 1)
            rungs.extend(range(int(lo), int(hi) + 1))
        else:
            rungs.append(int(part))
    return rungs


def _extract_rungs(source: str) -> list[tuple[int, int, int, str]]:
    """Extract rung boundaries from pyrung source.

    Returns list of (rung_number, start_line, end_line, first_comment).
    Detects ``# RN`` markers on ``with rung():`` lines.
    """
    lines = source.splitlines()
    rungs: list[tuple[int, int, int, str]] = []
    rung_marker = re.compile(r"#\s*R(\d+)\s*$")

    for i, line in enumerate(lines):
        m = rung_marker.search(line)
        if m:
            rung_num = int(m.group(1))
            comment = ""
            if i + 1 < len(lines):
                next_line = lines[i + 1].strip()
                if next_line.startswith("#"):
                    comment = next_line.lstrip("# ")
                elif next_line.startswith('"""') or next_line.startswith("'"):
                    comment = next_line.strip("\"' ")
            rungs.append((rung_num, i, 0, comment))

    for idx in range(len(rungs) - 1):
        num, start, _, comment = rungs[idx]
        rungs[idx] = (num, start, rungs[idx + 1][1], comment)
    if rungs:
        num, start, _, comment = rungs[-1]
        rungs[-1] = (num, start, len(lines), comment)

    return rungs


def _cmd_list(ctx: DispatchContext, parts: list[str]) -> str:
    file_stem = parts[0] if parts else None
    project_dir = _get_project_dir(ctx)

    if file_stem is None:
        return "files: " + ", ".join(_all_file_stems(project_dir))

    path = _resolve_file(project_dir, file_stem)
    source = path.read_text(encoding="utf-8")
    rungs = _extract_rungs(source)

    if not rungs:
        return f"{file_stem}: no rungs found"

    lines = []
    for rung_num, start, end, comment in rungs:
        row_count = end - start
        desc = f"  R{rung_num}: {row_count} lines"
        if comment:
            desc += f"  # {comment}"
        lines.append(desc)
    return f"{file_stem}: {len(rungs)} rungs\n" + "\n".join(lines)


_HUNK_RE = re.compile(r"^@@ -(\d+)")


def _annotate_hunk_headers(diff_lines: list[str], before_lines: list[str]) -> list[str]:
    """Add rung markers to @@ hunk headers, like git's function-context display."""
    rung_marker = re.compile(r"#\s*R(\d+)\s*$")
    result: list[str] = []
    for line in diff_lines:
        m = _HUNK_RE.match(line)
        if m:
            start = int(m.group(1)) - 1
            for i in range(min(start, len(before_lines) - 1), -1, -1):
                rm = rung_marker.search(before_lines[i])
                if rm:
                    rung_tag = f"  # R{rm.group(1)}"
                    line = line.rstrip() + rung_tag + "\n"
                    break
        result.append(line)
    return result


def _extract_changed_rungs(diff_lines: list[str]) -> list[int]:
    """Scan a unified diff for ``# RN`` rung markers in changed hunks."""
    found: set[int] = set()
    current_rung: int | None = None
    for line in diff_lines:
        if line.startswith("@@"):
            m = re.search(r"#\s*R(\d+)\s*$", line)
            current_rung = int(m.group(1)) if m else None
            continue
        m = re.search(r"#\s*R(\d+)\s*$", line)
        if m:
            current_rung = int(m.group(1))
        if (
            current_rung is not None
            and line.startswith(("+", "-"))
            and not line.startswith(("+++", "---"))
        ):
            found.add(current_rung)
    return sorted(found)


def _filter_diff_by_rungs(diff_lines: list[str], rung_nums: set[int]) -> list[str]:
    """Filter unified diff to only show hunks touching the selected rungs."""
    result: list[str] = []
    in_header = True
    include_hunk = False

    for line in diff_lines:
        if line.startswith("---") or line.startswith("+++"):
            result.append(line)
            continue
        if line.startswith("@@"):
            in_header = False
            include_hunk = False
            result.append(line)
            continue
        if not in_header:
            rung_match = re.search(r"#\s*R(\d+)\s*$", line)
            if rung_match and int(rung_match.group(1)) in rung_nums:
                include_hunk = True
            if include_hunk:
                result.append(line)

    return (
        result
        if any(ln.startswith(("+", "-")) and not ln.startswith(("---", "+++")) for ln in result)
        else []
    )


def _diff_one_file(
    project_dir: Path,
    before_files: dict[str, str],
    stem: str,
) -> tuple[list[str], list[int]]:
    """Compute unified diff and changed rungs for a single file stem.

    Returns (diff_lines, changed_rungs).  diff_lines is empty when unchanged.
    """
    path = _resolve_file(project_dir, stem)
    after = path.read_text(encoding="utf-8")

    relative_key = f"subroutines/{stem}.py" if stem != "main" else "main.py"
    before = before_files.get(relative_key, "")
    if not before:
        return [], []

    before_lines = before.splitlines(keepends=True)
    after_lines = after.splitlines(keepends=True)

    diff_lines = list(
        difflib.unified_diff(
            before_lines, after_lines, fromfile=f"a/{stem}.py", tofile=f"b/{stem}.py"
        )
    )
    diff_lines = _annotate_hunk_headers(diff_lines, before_lines)
    changed_rungs = _extract_changed_rungs(diff_lines) if diff_lines else []
    return diff_lines, changed_rungs


def _preview_all(project_dir: Path, before_files: dict[str, str]) -> str:
    """Scan all files and summarize which ones have changes."""
    changed: list[str] = []
    for stem in _all_file_stems(project_dir):
        _, rungs = _diff_one_file(project_dir, before_files, stem)
        if rungs:
            changed.append(f"  {stem}: {', '.join(f'R{r}' for r in rungs)}")
    if not changed:
        return "(no changes)"
    return "changed files:\n" + "\n".join(changed)


def _cmd_preview(ctx: DispatchContext, parts: list[str]) -> str:
    file_stem = None
    selection = None

    i = 0
    while i < len(parts):
        if parts[i] == "--select" and i + 1 < len(parts):
            selection = parts[i + 1]
            i += 2
        elif file_stem is None:
            file_stem = parts[i]
            i += 1
        else:
            raise ValueError(f"unexpected argument: {parts[i]}")

    project_dir = _get_project_dir(ctx)
    before_files = _get_before_files(project_dir)

    if file_stem is None and selection is None:
        return _preview_all(project_dir, before_files)

    label = file_stem or "main"
    diff_lines, changed_rungs = _diff_one_file(project_dir, before_files, label)

    if not diff_lines:
        return "(no changes)"

    if selection:
        rung_nums_list = _parse_rung_selection(selection)
        filtered = _filter_diff_by_rungs(diff_lines, set(rung_nums_list))
        if not filtered:
            return f"(no changes in selected rungs: {selection})"
        diff_text = "".join(filtered)
    else:
        rung_nums_list = changed_rungs if changed_rungs else None
        diff_text = "".join(diff_lines)

    if ctx.show_preview is not None:
        pending_dir = project_dir / "csv_output"
        ctx.show_preview(
            label,
            selection,
            diff_text,
            rung_nums_list,
            pending_dir if pending_dir.is_dir() else None,
        )
        n = len(rung_nums_list) if rung_nums_list else "all"
        return f"OK: preview window opened for {label} ({n} rungs)"

    return diff_text


def _cmd_apply(ctx: DispatchContext, parts: list[str]) -> str:
    import subprocess

    project_dir = _get_project_dir(ctx)
    script = project_dir / "project_to_csv.py"
    if not script.is_file():
        raise ValueError("project_to_csv.py not found in project directory")

    result = subprocess.run(
        [sys.executable, str(script)],
        cwd=str(project_dir),
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        raise ValueError(
            result.stderr.strip() or f"project_to_csv.py exited with code {result.returncode}"
        )

    pending_dir = project_dir / "csv_output"
    return f"OK: wrote ladder CSVs to {pending_dir}"


_SUBCOMMANDS = {
    "list": _cmd_list,
    "preview": _cmd_preview,
    "apply": _cmd_apply,
}


def dispatch_rung(ctx: DispatchContext, parts: list[str]) -> str:
    """Route ``rung <subcommand> ...`` to the right handler."""
    if not parts:
        raise ValueError(f"usage: rung <subcommand> ...  (subcommands: {', '.join(_SUBCOMMANDS)})")

    sub = parts[0].lower()
    handler = _SUBCOMMANDS.get(sub)
    if handler is None:
        raise ValueError(f"unknown rung subcommand {sub!r} (expected: {', '.join(_SUBCOMMANDS)})")
    return handler(ctx, parts[1:])
