"""Rung commands for live editing.

Program listing, preview, and reverse-path (pyrung -> ladder) operations.
Reads from the persisted pyrung_project/ directory generated by AnalysisService.
"""

from __future__ import annotations

import difflib
import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .dispatch import DispatchContext


def _get_project_dir(ctx: DispatchContext) -> Path:
    """Get the persisted pyrung_project directory, or raise."""
    analysis = ctx.analysis
    if analysis is None or not analysis.is_available:
        raise ValueError("analysis not available (no Click project connected or build pending)")
    project_dir = analysis.project_dir
    if project_dir is None or not project_dir.is_dir():
        raise ValueError("pyrung project not persisted to disk yet")
    return project_dir


def _resolve_file(project_dir: Path, file_stem: str | None) -> Path:
    """Resolve a file stem (e.g. 'main', 'startup') to a .py path in the project."""
    if file_stem is None or file_stem == "main":
        path = project_dir / "main.py"
    else:
        path = project_dir / "subroutines" / f"{file_stem}.py"
    if not path.is_file():
        raise ValueError(f"file not found: {path}")
    return path


def _parse_rung_selection(selection: str) -> list[int]:
    """Parse rung selection: r3, r1..5, r3,r7 -> list of 1-based rung numbers."""
    parts = selection.upper().replace("R", "").split(",")
    rungs: list[int] = []
    for part in parts:
        part = part.strip()
        if ".." in part:
            lo, hi = part.split("..", 1)
            rungs.extend(range(int(lo), int(hi) + 1))
        else:
            rungs.append(int(part))
    return rungs


def _extract_rungs(source: str) -> list[tuple[int, int, int, str]]:
    """Extract rung boundaries from pyrung source.

    Returns list of (rung_number, start_line, end_line, first_comment).
    Detects ``def rung_N`` or ``# R<N>`` markers.
    """
    lines = source.splitlines()
    rungs: list[tuple[int, int, int, str]] = []
    rung_pattern = re.compile(r"^def rung_(\d+)\(")
    marker_pattern = re.compile(r"^# R(\d+)")

    for i, line in enumerate(lines):
        m = rung_pattern.match(line) or marker_pattern.match(line)
        if m:
            rung_num = int(m.group(1))
            comment = ""
            if i + 1 < len(lines):
                next_line = lines[i + 1].strip()
                if next_line.startswith("#"):
                    comment = next_line.lstrip("# ")
                elif next_line.startswith('"""') or next_line.startswith("'"):
                    comment = next_line.strip("\"' ")
            rungs.append((rung_num, i, 0, comment))

    for idx in range(len(rungs) - 1):
        num, start, _, comment = rungs[idx]
        rungs[idx] = (num, start, rungs[idx + 1][1], comment)
    if rungs:
        num, start, _, comment = rungs[-1]
        rungs[-1] = (num, start, len(lines), comment)

    return rungs


def _cmd_list(ctx: DispatchContext, parts: list[str]) -> str:
    file_stem = parts[0] if parts else None
    project_dir = _get_project_dir(ctx)

    if file_stem is None:
        available = ["main"]
        sub_dir = project_dir / "subroutines"
        if sub_dir.is_dir():
            available.extend(p.stem for p in sorted(sub_dir.glob("*.py")))
        return "files: " + ", ".join(available)

    path = _resolve_file(project_dir, file_stem)
    source = path.read_text(encoding="utf-8")
    rungs = _extract_rungs(source)

    if not rungs:
        return f"{file_stem}: no rungs found"

    lines = []
    for rung_num, start, end, comment in rungs:
        row_count = end - start
        desc = f"  R{rung_num}: {row_count} lines"
        if comment:
            desc += f"  # {comment}"
        lines.append(desc)
    return f"{file_stem}: {len(rungs)} rungs\n" + "\n".join(lines)


def _filter_diff_by_rungs(diff_lines: list[str], rung_nums: set[int]) -> list[str]:
    """Filter unified diff to only show hunks touching the selected rungs."""
    result: list[str] = []
    in_header = True
    include_hunk = False

    for line in diff_lines:
        if line.startswith("---") or line.startswith("+++"):
            result.append(line)
            continue
        if line.startswith("@@"):
            in_header = False
            include_hunk = False
            result.append(line)
            continue
        if not in_header:
            rung_match = re.search(r"rung_(\d+)", line)
            if rung_match and int(rung_match.group(1)) in rung_nums:
                include_hunk = True
            if include_hunk:
                result.append(line)

    return (
        result
        if any(ln.startswith(("+", "-")) and not ln.startswith(("---", "+++")) for ln in result)
        else []
    )


def _cmd_preview(ctx: DispatchContext, parts: list[str]) -> str:
    file_stem = None
    selection = None

    i = 0
    while i < len(parts):
        if parts[i] == "--select" and i + 1 < len(parts):
            selection = parts[i + 1]
            i += 2
        elif file_stem is None:
            file_stem = parts[i]
            i += 1
        else:
            raise ValueError(f"unexpected argument: {parts[i]}")

    project_dir = _get_project_dir(ctx)
    path = _resolve_file(project_dir, file_stem)
    before = path.read_text(encoding="utf-8")

    assert ctx.store is not None
    nicknames: dict[str, str] = {}
    for _addr_key, row in ctx.store.visible_state.items():
        if row.nickname:
            nicknames[row.display_address] = row.nickname

    from pyrung.click import ladder_to_pyrung

    analysis = ctx.analysis
    assert analysis is not None
    csv_dir = project_dir.parent
    nickname_csv = csv_dir / "nicknames.csv" if (csv_dir / "nicknames.csv").exists() else None

    after = ladder_to_pyrung(csv_dir, nickname_csv=nickname_csv, nicknames=nicknames)

    before_lines = before.splitlines(keepends=True)
    after_lines = after.splitlines(keepends=True)

    label = file_stem or "main"
    diff_lines = list(
        difflib.unified_diff(
            before_lines, after_lines, fromfile=f"a/{label}.py", tofile=f"b/{label}.py"
        )
    )

    if selection:
        rung_nums = set(_parse_rung_selection(selection))
        filtered = _filter_diff_by_rungs(diff_lines, rung_nums)
        if not filtered:
            return f"(no changes in selected rungs: {selection})"
        return "".join(filtered)

    if not diff_lines:
        return "(no changes)"
    return "".join(diff_lines)


def _cmd_apply(ctx: DispatchContext, parts: list[str]) -> str:
    file_stem = parts[0] if parts else None
    project_dir = _get_project_dir(ctx)
    path = _resolve_file(project_dir, file_stem)

    source = path.read_text(encoding="utf-8")

    namespace: dict[str, object] = {}
    exec(compile(source, str(path), "exec"), namespace)  # noqa: S102

    from pyrung.core.program import Program

    program = namespace.get("logic")
    if not isinstance(program, Program):
        raise ValueError(f"no valid Program found in {path.name}")

    tags_path = project_dir / "tags.py"
    if not tags_path.is_file():
        raise ValueError("tags.py not found in project directory")
    tags_ns: dict[str, object] = {}
    exec(compile(tags_path.read_text(encoding="utf-8"), str(tags_path), "exec"), tags_ns)  # noqa: S102

    from pyrung.click.tag_map import TagMap

    tag_map = tags_ns.get("tags")
    if not isinstance(tag_map, TagMap):
        raise ValueError("no valid TagMap found in tags.py")

    from pyrung.click import pyrung_to_ladder

    bundle = pyrung_to_ladder(program, tag_map, index=True)

    pending_dir = project_dir / "pending"
    bundle.write(pending_dir)

    return f"OK: wrote ladder CSVs to {pending_dir}"


_SUBCOMMANDS = {
    "list": _cmd_list,
    "preview": _cmd_preview,
    "apply": _cmd_apply,
}


def dispatch_rung(ctx: DispatchContext, parts: list[str]) -> str:
    """Route ``rung <subcommand> ...`` to the right handler."""
    if not parts:
        raise ValueError(f"usage: rung <subcommand> ...  (subcommands: {', '.join(_SUBCOMMANDS)})")

    sub = parts[0].lower()
    handler = _SUBCOMMANDS.get(sub)
    if handler is None:
        raise ValueError(f"unknown rung subcommand {sub!r} (expected: {', '.join(_SUBCOMMANDS)})")
    return handler(ctx, parts[1:])
