"""Project-local sidecars and durable active-workspace configuration."""

from __future__ import annotations

import datetime as dt
import json
import os
import shutil
import tempfile
import tomllib
from configparser import ConfigParser
from configparser import Error as ConfigParserError
from dataclasses import dataclass
from pathlib import Path

from ..models.name_validation import validate_click_name

SIDECAR_NAME = ".clicknick.toml"

# These paths are regenerated by ClickNick and may be updated in a workspace.
MIRROR_OWNED_DIRS = (Path("src") / "plc", Path("csv"))
MIRROR_OWNED_FILES = (
    Path("nicknames.csv"),
    Path("project_to_csv.py"),
    Path("run.py"),
)

# Everything else is copied only when absent. This seeds a new mirror while
# preserving user-owned tests, docs, environments, and editor configuration.
_NEVER_MIRROR_NAMES = {
    SIDECAR_NAME,
    ".venv",
    "__pycache__",
    "backup",
    "csv_output",
}
_NEVER_MIRROR_SUFFIXES = {".pyc"}


def _normalized(path: Path) -> Path:
    return Path(os.path.normpath(path.resolve(strict=False)))


def sidecar_path_for(workspace: Path) -> Path:
    """Return the self-contained metadata path for *workspace*."""
    return _normalized(workspace) / SIDECAR_NAME


@dataclass(frozen=True)
class ProjectWorkspaceConfig:
    """One durable workspace identified by CLICK's configured PLC name."""

    plc_name: str
    workspace_path: Path

    @property
    def sidecar_path(self) -> Path:
        return sidecar_path_for(self.workspace_path)


@dataclass(frozen=True)
class MirrorSyncResult:
    copied_files: int
    mirror_path: Path


@dataclass(frozen=True)
class WorkspaceDirectoryInfo:
    """Directory metadata consumed by the Workspace details surface."""

    generated_dir: Path | None
    config_path: Path | None
    mirror_dir: Path | None
    last_regenerated_at: dt.datetime | None
    last_backup_at: dt.datetime | None


def workspace_path_for_selection(selection: Path, plc_name: str) -> Path:
    """Resolve a selected home to ``<PLC name> Workspace``."""
    is_valid, error = validate_click_name(plc_name)
    if not is_valid:
        raise ValueError(error)
    selection = _normalized(selection)
    return selection / f"{plc_name.strip()} Workspace"


def save_project_workspace_config(config: ProjectWorkspaceConfig) -> Path:
    """Atomically write a PLC-owned active-workspace configuration."""
    is_valid, error = validate_click_name(config.plc_name)
    if not is_valid:
        raise ValueError(error)
    sidecar = _normalized(config.sidecar_path)
    sidecar.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# ClickNick uses this as the active workspace for the named CLICK PLC.",
        "# ClickNick owns generated PLC source/data and preserves tests, docs, and tooling.",
        "",
        "version = 1",
        "",
        "[plc]",
        f"name = {json.dumps(config.plc_name.strip())}",
    ]
    lines.append("")

    staging = sidecar.with_suffix(f"{sidecar.suffix}.staging")
    staging.write_text("\n".join(lines), encoding="utf-8")
    staging.replace(sidecar)
    return sidecar


def load_project_workspace_config(sidecar: Path) -> ProjectWorkspaceConfig:
    """Load and validate a PLC-owned workspace sidecar."""
    sidecar = _normalized(sidecar)
    if sidecar.name.casefold() != SIDECAR_NAME.casefold():
        raise ValueError(f"not a ClickNick project sidecar: {sidecar}")
    try:
        data = tomllib.loads(sidecar.read_text(encoding="utf-8"))
        if data.get("version") != 1:
            raise ValueError("unsupported sidecar version")
        plc_name = data["plc"]["name"]
        if not isinstance(plc_name, str):
            raise ValueError("plc.name must be a string")
        is_valid, error = validate_click_name(plc_name)
        if not is_valid:
            raise ValueError(error)
    except (KeyError, OSError, TypeError, UnicodeError, tomllib.TOMLDecodeError) as exc:
        raise ValueError(f"invalid ClickNick project sidecar: {sidecar}") from exc

    return ProjectWorkspaceConfig(
        plc_name=plc_name.strip(),
        workspace_path=sidecar.parent,
    )


def read_plc_name(project_ini: Path) -> str | None:
    """Read CLICK's configured PLC name from a temporary ``Project.ini``."""
    parser = ConfigParser(interpolation=None)
    try:
        with Path(project_ini).open(encoding="utf-8-sig") as stream:
            parser.read_file(stream)
        value = parser.get("PLCName", "PLCName", fallback="").strip()
    except (ConfigParserError, OSError, UnicodeError):
        return None
    return value or None


def write_plc_name(project_ini: Path, plc_name: str) -> None:
    """Atomically set CLICK's PLC name while preserving the rest of Project.ini."""
    is_valid, error = validate_click_name(plc_name)
    if not is_valid:
        raise ValueError(error)
    project_ini = _normalized(project_ini)
    original = project_ini.read_bytes()
    newline = b"\r\n" if b"\r\n" in original else b"\n"
    lines = original.splitlines(keepends=True)
    section_start = None
    section_end = len(lines)
    for index, line in enumerate(lines):
        stripped = line.strip().lower()
        if stripped == b"[plcname]":
            section_start = index
        elif section_start is not None and stripped.startswith(b"[") and stripped.endswith(b"]"):
            section_end = index
            break

    entry = b"PLCName=" + plc_name.strip().encode("ascii") + newline
    if section_start is None:
        if original and not original.endswith((b"\r", b"\n")):
            lines.append(newline)
        lines.extend((b"[PLCName]" + newline, entry))
    else:
        for index in range(section_start + 1, section_end):
            if lines[index].split(b"=", 1)[0].strip().lower() == b"plcname":
                lines[index] = entry
                break
        else:
            lines.insert(section_start + 1, entry)

    descriptor, staging_value = tempfile.mkstemp(
        prefix=f".{project_ini.name}.", suffix=".clicknick-name", dir=project_ini.parent
    )
    os.close(descriptor)
    staging = Path(staging_value)
    try:
        staging.write_bytes(b"".join(lines))
        staging.replace(project_ini)
        if read_plc_name(project_ini) != plc_name.strip():
            project_ini.write_bytes(original)
            raise OSError("CLICK PLC name could not be verified")
    finally:
        staging.unlink(missing_ok=True)


def default_locator_path() -> Path:
    """Return the non-authoritative index of known project sidecars."""
    local_app_data = os.environ.get("LOCALAPPDATA")
    root = Path(local_app_data) if local_app_data else Path.home() / "AppData" / "Local"
    return root / "ClickNick" / "project-sidecars.json"


def _read_locator(locator_path: Path) -> tuple[list[Path], dict[str, Path]]:
    try:
        data = json.loads(locator_path.read_text(encoding="utf-8"))
        values = data.get("sidecars", [])
        if not isinstance(values, list):
            return [], {}
        preferred_values = data.get("preferred", {})
        preferred = (
            {
                key: _normalized(Path(value))
                for key, value in preferred_values.items()
                if isinstance(key, str) and isinstance(value, str)
            }
            if isinstance(preferred_values, dict)
            else {}
        )
        return (
            [_normalized(Path(value)) for value in values if isinstance(value, str)],
            preferred,
        )
    except (OSError, TypeError, ValueError):
        return [], {}


def remember_project_sidecar(
    sidecar: Path,
    locator_path: Path | None = None,
    *,
    preferred_for: str | None = None,
) -> Path:
    """Remember where a sidecar lives without duplicating its configuration."""
    locator_path = _normalized(locator_path or default_locator_path())
    sidecar = _normalized(sidecar)
    known_paths, preferred = _read_locator(locator_path)
    known = {path for path in known_paths if path.is_file()}
    known.add(sidecar)
    if preferred_for:
        preferred[preferred_for.strip().casefold()] = sidecar
    locator_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 1,
        "sidecars": [str(path) for path in sorted(known)],
        "preferred": {key: str(path) for key, path in sorted(preferred.items())},
    }
    staging = locator_path.with_suffix(f"{locator_path.suffix}.staging")
    staging.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    staging.replace(locator_path)
    return locator_path


def find_project_configs(
    plc_name: str,
    locator_path: Path | None = None,
) -> list[ProjectWorkspaceConfig]:
    """Return known valid sidecars matching a connected PLC name."""
    locator_path = _normalized(locator_path or default_locator_path())
    matches: list[ProjectWorkspaceConfig] = []
    sidecars, _ = _read_locator(locator_path)
    for sidecar in sidecars:
        if not sidecar.is_file():
            continue
        try:
            config = load_project_workspace_config(sidecar)
        except ValueError:
            continue
        if config.plc_name.casefold() == plc_name.strip().casefold():
            matches.append(config)
    return matches


def preferred_project_config(
    plc_name: str,
    configs: list[ProjectWorkspaceConfig],
    locator_path: Path | None = None,
) -> ProjectWorkspaceConfig | None:
    """Return the user's remembered choice when it remains a valid match."""
    locator_path = _normalized(locator_path or default_locator_path())
    _, preferred = _read_locator(locator_path)
    preferred_path = preferred.get(plc_name.strip().casefold())
    if preferred_path is None:
        return None
    return next((config for config in configs if config.sidecar_path == preferred_path), None)


def _is_ignored(path: Path) -> bool:
    return any(part in _NEVER_MIRROR_NAMES for part in path.parts) or (
        path.suffix in _NEVER_MIRROR_SUFFIXES
    )


def _copy_file(source: Path, destination: Path, *, overwrite: bool) -> bool:
    if destination.exists() and not overwrite:
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, staging_value = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".clicknick-sync", dir=destination.parent
    )
    os.close(descriptor)
    staging = Path(staging_value)
    try:
        shutil.copy2(source, staging)
        staging.replace(destination)
    finally:
        staging.unlink(missing_ok=True)
    return True


def _copy_tree(source: Path, destination: Path, *, overwrite: bool) -> int:
    copied = 0
    if not source.is_dir():
        return copied
    for path in source.rglob("*"):
        relative = path.relative_to(source)
        if not path.is_file() or _is_ignored(relative):
            continue
        copied += _copy_file(path, destination / relative, overwrite=overwrite)
    return copied


def validate_mirror_destination(source: Path, mirror: Path) -> None:
    """Reject a new workspace that overlaps the current active workspace."""
    source = _normalized(source)
    mirror = _normalized(mirror)
    if source == mirror or source in mirror.parents or mirror in source.parents:
        raise ValueError("workspace directory must be separate from the active workspace")


def sync_workspace_to_mirror(source: Path, mirror: Path) -> MirrorSyncResult:
    """Overlay the active workspace onto a mirror without deleting target files."""
    source = _normalized(source)
    mirror = _normalized(mirror)
    if not source.is_dir():
        raise ValueError(f"active workspace directory not found: {source}")
    if not (source / "src" / "plc").is_dir():
        raise ValueError(f"active workspace source not found: {source / 'src' / 'plc'}")
    validate_mirror_destination(source, mirror)
    mirror.mkdir(parents=True, exist_ok=True)

    copied = 0
    owned_roots = set(MIRROR_OWNED_DIRS)
    for relative in MIRROR_OWNED_DIRS:
        copied += _copy_tree(source / relative, mirror / relative, overwrite=True)
    for relative in MIRROR_OWNED_FILES:
        source_file = source / relative
        if source_file.is_file():
            copied += _copy_file(source_file, mirror / relative, overwrite=True)

    # Seed all other useful workspace files only when the mirror does not
    # already own a copy. No target file is ever removed.
    for path in source.rglob("*"):
        relative = path.relative_to(source)
        if not path.is_file() or _is_ignored(relative):
            continue
        if any(relative == root or root in relative.parents for root in owned_roots):
            continue
        if relative in MIRROR_OWNED_FILES:
            continue
        copied += _copy_file(path, mirror / relative, overwrite=False)

    return MirrorSyncResult(copied, mirror)


def _latest_mtime(root: Path) -> dt.datetime | None:
    try:
        timestamps = [path.stat().st_mtime for path in root.rglob("*") if path.is_file()]
    except OSError:
        return None
    if not timestamps:
        return None
    return dt.datetime.fromtimestamp(max(timestamps)).astimezone()


def get_workspace_directory_info(
    config: ProjectWorkspaceConfig | None, generated_dir: Path | None
) -> WorkspaceDirectoryInfo:
    """Collect paths and timestamps without requiring a Tkinter view."""
    generated_dir = _normalized(generated_dir) if generated_dir is not None else None
    config_path = config.sidecar_path if config is not None else None
    mirror_dir = config.workspace_path if config is not None else None
    last_regenerated_at = None
    last_backup_at = None
    if generated_dir is not None:
        state_file = generated_dir / "backup" / "generated-source.json"
        try:
            last_regenerated_at = dt.datetime.fromtimestamp(state_file.stat().st_mtime).astimezone()
        except OSError:
            pass
        last_backup_at = _latest_mtime(generated_dir / "backup" / "src" / "plc")
    return WorkspaceDirectoryInfo(
        generated_dir=generated_dir,
        config_path=config_path,
        mirror_dir=mirror_dir,
        last_regenerated_at=last_regenerated_at,
        last_backup_at=last_backup_at,
    )
