"""Project-local pairing and conservative one-way workspace mirroring."""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import shutil
import tempfile
import tomllib
from dataclasses import dataclass, replace
from enum import Enum
from pathlib import Path

SIDECAR_SUFFIX = ".clicknick.toml"

# These paths are regenerated by ClickNick and may be updated in a mirror.
MIRROR_OWNED_DIRS = (Path("src") / "plc", Path("csv"))
MIRROR_OWNED_FILES = (
    Path("nicknames.csv"),
    Path("project_to_csv.py"),
    Path("run.py"),
)

# Everything else is copied only when absent. This seeds a new mirror while
# preserving user-owned tests, docs, environments, and editor configuration.
_NEVER_MIRROR_NAMES = {".venv", "__pycache__", "backup", "csv_output"}
_NEVER_MIRROR_SUFFIXES = {".pyc"}


class MirrorState(Enum):
    NOT_CONFIGURED = "not_configured"
    PAIRED = "paired"
    SYNCED = "synced"
    ERROR = "error"


def sidecar_path_for(project_file: Path) -> Path:
    """Return ``Example Project.clicknick.toml`` for a ``.ckp`` file."""
    project_file = Path(project_file)
    return project_file.with_suffix(SIDECAR_SUFFIX)


@dataclass(frozen=True)
class ProjectWorkspaceConfig:
    """Pairing stored beside one CLICK project file."""

    project_file: Path
    mirror_path: Path
    last_synced_at: dt.datetime | None = None

    @property
    def sidecar_path(self) -> Path:
        return sidecar_path_for(self.project_file)


@dataclass(frozen=True)
class MirrorStatus:
    state: MirrorState
    label: str
    path: Path | None = None
    detail: str | None = None
    last_synced_at: dt.datetime | None = None


@dataclass(frozen=True)
class MirrorSyncResult:
    copied_files: int
    mirror_path: Path
    synced_at: dt.datetime


@dataclass(frozen=True)
class WorkspaceDirectoryInfo:
    """Directory metadata consumed by the Workspace details surface."""

    generated_dir: Path | None
    source_project: Path | None
    mirror_dir: Path | None
    last_regenerated_at: dt.datetime | None
    last_backup_at: dt.datetime | None


def _normalized(path: Path) -> Path:
    return Path(os.path.normpath(path.resolve(strict=False)))


def _stored_mirror_path(project_file: Path, mirror_path: Path) -> str:
    project_parent = _normalized(project_file).parent
    mirror_path = _normalized(mirror_path)
    try:
        relative = mirror_path.relative_to(project_parent)
    except ValueError:
        return str(mirror_path)
    return relative.as_posix() or "."


def save_project_workspace_config(config: ProjectWorkspaceConfig) -> Path:
    """Atomically write project-specific mirror configuration."""
    project_file = _normalized(config.project_file)
    sidecar = sidecar_path_for(project_file)
    sidecar.parent.mkdir(parents=True, exist_ok=True)
    mirror_value = _stored_mirror_path(project_file, config.mirror_path)
    lines = [
        "# One-way only: generated ClickNick workspace -> mirror.",
        "# ClickNick replaces src/plc, csv, nicknames.csv, project_to_csv.py, and run.py.",
        "# Sync never deletes files from the mirror.",
        "",
        "version = 1",
        "",
        "[workspace]",
        f"mirror_path = {json.dumps(mirror_value)}",
    ]
    if config.last_synced_at is not None:
        lines.append(f"last_synced_at = {json.dumps(config.last_synced_at.isoformat())}")
    lines.append("")

    staging = sidecar.with_suffix(f"{sidecar.suffix}.staging")
    staging.write_text("\n".join(lines), encoding="utf-8")
    staging.replace(sidecar)
    return sidecar


def load_project_workspace_config(sidecar: Path) -> ProjectWorkspaceConfig:
    """Load and validate a project sidecar."""
    sidecar = _normalized(sidecar)
    if not sidecar.name.lower().endswith(SIDECAR_SUFFIX):
        raise ValueError(f"not a ClickNick project sidecar: {sidecar}")
    try:
        data = tomllib.loads(sidecar.read_text(encoding="utf-8"))
        if data.get("version") != 1:
            raise ValueError("unsupported sidecar version")
        workspace = data["workspace"]
        mirror_value = workspace["mirror_path"]
        if not isinstance(mirror_value, str) or not mirror_value.strip():
            raise ValueError("workspace.mirror_path must be a non-empty string")
    except (KeyError, OSError, TypeError, UnicodeError, tomllib.TOMLDecodeError) as exc:
        raise ValueError(f"invalid ClickNick project sidecar: {sidecar}") from exc

    project_name = sidecar.name[: -len(SIDECAR_SUFFIX)] + ".ckp"
    project_file = sidecar.with_name(project_name)
    raw_mirror = Path(mirror_value)
    mirror_path = raw_mirror if raw_mirror.is_absolute() else sidecar.parent / raw_mirror

    last_synced_at = None
    raw_synced = workspace.get("last_synced_at")
    if raw_synced is not None:
        try:
            last_synced_at = dt.datetime.fromisoformat(raw_synced)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"invalid last_synced_at in sidecar: {sidecar}") from exc

    return ProjectWorkspaceConfig(
        project_file=_normalized(project_file),
        mirror_path=_normalized(mirror_path),
        last_synced_at=last_synced_at,
    )


def default_locator_path() -> Path:
    """Return the non-authoritative index of known project sidecars."""
    local_app_data = os.environ.get("LOCALAPPDATA")
    root = Path(local_app_data) if local_app_data else Path.home() / "AppData" / "Local"
    return root / "ClickNick" / "project-sidecars.json"


def _read_locator(locator_path: Path) -> list[Path]:
    try:
        data = json.loads(locator_path.read_text(encoding="utf-8"))
        values = data.get("sidecars", [])
        if not isinstance(values, list):
            return []
        return [_normalized(Path(value)) for value in values if isinstance(value, str)]
    except (OSError, TypeError, ValueError):
        return []


def remember_project_sidecar(sidecar: Path, locator_path: Path | None = None) -> Path:
    """Remember where a sidecar lives without duplicating its configuration."""
    locator_path = _normalized(locator_path or default_locator_path())
    sidecar = _normalized(sidecar)
    known = {path for path in _read_locator(locator_path) if path.is_file()}
    known.add(sidecar)
    locator_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"version": 1, "sidecars": [str(path) for path in sorted(known)]}
    staging = locator_path.with_suffix(f"{locator_path.suffix}.staging")
    staging.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    staging.replace(locator_path)
    return locator_path


def find_project_configs(
    project_filename: str, locator_path: Path | None = None
) -> list[ProjectWorkspaceConfig]:
    """Return known valid sidecars matching a connected CLICK filename."""
    locator_path = _normalized(locator_path or default_locator_path())
    matches: list[ProjectWorkspaceConfig] = []
    for sidecar in _read_locator(locator_path):
        if not sidecar.is_file():
            continue
        try:
            config = load_project_workspace_config(sidecar)
        except ValueError:
            continue
        if (
            config.project_file.is_file()
            and config.project_file.name.casefold() == project_filename.casefold()
        ):
            matches.append(config)
    return matches


def _is_ignored(path: Path) -> bool:
    return any(part in _NEVER_MIRROR_NAMES for part in path.parts) or (
        path.suffix in _NEVER_MIRROR_SUFFIXES
    )


def _copy_file(source: Path, destination: Path, *, overwrite: bool) -> bool:
    if destination.exists() and not overwrite:
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, staging_value = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".clicknick-sync", dir=destination.parent
    )
    os.close(descriptor)
    staging = Path(staging_value)
    try:
        shutil.copy2(source, staging)
        staging.replace(destination)
    finally:
        staging.unlink(missing_ok=True)
    return True


def _copy_tree(source: Path, destination: Path, *, overwrite: bool) -> int:
    copied = 0
    if not source.is_dir():
        return copied
    for path in source.rglob("*"):
        relative = path.relative_to(source)
        if not path.is_file() or _is_ignored(relative):
            continue
        copied += _copy_file(path, destination / relative, overwrite=overwrite)
    return copied


def validate_mirror_destination(source: Path, mirror: Path) -> None:
    """Reject mirror paths that overlap the active generated workspace."""
    source = _normalized(source)
    mirror = _normalized(mirror)
    if source == mirror or source in mirror.parents or mirror in source.parents:
        raise ValueError("mirror directory must be separate from the active workspace")


def sync_workspace_to_mirror(source: Path, mirror: Path) -> MirrorSyncResult:
    """Overlay the active workspace onto a mirror without deleting target files."""
    source = _normalized(source)
    mirror = _normalized(mirror)
    if not source.is_dir():
        raise ValueError(f"active workspace directory not found: {source}")
    if not (source / "src" / "plc").is_dir():
        raise ValueError(f"active workspace source not found: {source / 'src' / 'plc'}")
    validate_mirror_destination(source, mirror)
    mirror.mkdir(parents=True, exist_ok=True)

    copied = 0
    owned_roots = set(MIRROR_OWNED_DIRS)
    for relative in MIRROR_OWNED_DIRS:
        copied += _copy_tree(source / relative, mirror / relative, overwrite=True)
    for relative in MIRROR_OWNED_FILES:
        source_file = source / relative
        if source_file.is_file():
            copied += _copy_file(source_file, mirror / relative, overwrite=True)

    # Seed all other useful workspace files only when the mirror does not
    # already own a copy. No target file is ever removed.
    for path in source.rglob("*"):
        relative = path.relative_to(source)
        if not path.is_file() or _is_ignored(relative):
            continue
        if any(relative == root or root in relative.parents for root in owned_roots):
            continue
        if relative in MIRROR_OWNED_FILES:
            continue
        copied += _copy_file(path, mirror / relative, overwrite=False)

    return MirrorSyncResult(copied, mirror, dt.datetime.now().astimezone())


def _file_digest(path: Path) -> bytes:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.digest()


def _owned_files_match(source: Path, mirror: Path) -> bool:
    for relative_root in MIRROR_OWNED_DIRS:
        source_root = source / relative_root
        for source_file in source_root.rglob("*") if source_root.is_dir() else ():
            relative = source_file.relative_to(source)
            if not source_file.is_file() or _is_ignored(relative):
                continue
            mirror_file = mirror / relative
            if not mirror_file.is_file():
                return False
            if _file_digest(source_file) != _file_digest(mirror_file):
                return False
    for relative in MIRROR_OWNED_FILES:
        source_file = source / relative
        if not source_file.is_file():
            continue
        mirror_file = mirror / relative
        if not mirror_file.is_file() or _file_digest(source_file) != _file_digest(mirror_file):
            return False
    return True


def get_mirror_status(
    config: ProjectWorkspaceConfig | None,
    source: Path | None,
    *,
    error: str | None = None,
) -> MirrorStatus:
    """Describe pairing/sync state for the Workspace details surface."""
    if config is None:
        return MirrorStatus(MirrorState.NOT_CONFIGURED, "Not configured")
    if error:
        return MirrorStatus(
            MirrorState.ERROR,
            "Error",
            path=config.mirror_path,
            detail=error,
            last_synced_at=config.last_synced_at,
        )
    if source is not None and source.is_dir() and config.mirror_path.is_dir():
        try:
            if _owned_files_match(source, config.mirror_path):
                return MirrorStatus(
                    MirrorState.SYNCED,
                    "Synced",
                    path=config.mirror_path,
                    last_synced_at=config.last_synced_at,
                )
        except OSError as exc:
            return MirrorStatus(
                MirrorState.ERROR,
                "Error",
                path=config.mirror_path,
                detail=str(exc),
                last_synced_at=config.last_synced_at,
            )
    return MirrorStatus(
        MirrorState.PAIRED,
        "Paired",
        path=config.mirror_path,
        last_synced_at=config.last_synced_at,
    )


def record_successful_sync(
    config: ProjectWorkspaceConfig, result: MirrorSyncResult
) -> ProjectWorkspaceConfig:
    """Persist a successful sync timestamp and return the updated config."""
    updated = replace(config, last_synced_at=result.synced_at)
    save_project_workspace_config(updated)
    return updated


def _latest_mtime(root: Path) -> dt.datetime | None:
    try:
        timestamps = [path.stat().st_mtime for path in root.rglob("*") if path.is_file()]
    except OSError:
        return None
    if not timestamps:
        return None
    return dt.datetime.fromtimestamp(max(timestamps)).astimezone()


def get_workspace_directory_info(
    config: ProjectWorkspaceConfig | None, generated_dir: Path | None
) -> WorkspaceDirectoryInfo:
    """Collect paths and timestamps without requiring a Tkinter view."""
    generated_dir = _normalized(generated_dir) if generated_dir is not None else None
    source_project = config.project_file if config is not None else None
    mirror_dir = config.mirror_path if config is not None else None
    last_regenerated_at = None
    last_backup_at = None
    if generated_dir is not None:
        state_file = generated_dir / "backup" / "generated-source.json"
        try:
            last_regenerated_at = dt.datetime.fromtimestamp(state_file.stat().st_mtime).astimezone()
        except OSError:
            pass
        last_backup_at = _latest_mtime(generated_dir / "backup" / "src" / "plc")
    return WorkspaceDirectoryInfo(
        generated_dir=generated_dir,
        source_project=source_project,
        mirror_dir=mirror_dir,
        last_regenerated_at=last_regenerated_at,
        last_backup_at=last_backup_at,
    )
