"""Ladder module — re-exports from laddercodec plus local clipboard helpers."""

from laddercodec import (
    CELL_HORIZONTAL_LEFT_OFFSET,
    CELL_HORIZONTAL_RIGHT_OFFSET,
    CELL_VERTICAL_DOWN_OFFSET,
    EMPTY_MULTIROW_MAX_ROWS,
    EMPTY_MULTIROW_MIN_ROWS,
    CellWireFlags,
    ClickCodec,
    Coil,
    Contact,
    EncodeResult,
    HeaderSeed,
    InstructionType,
    LadderRungV2,
    RungGrid,
    V2Degradation,
    V2EncodeReport,
    V2UnsupportedShapeError,
    WireCellTopology,
    WireTopology,
    empty_multirow_payload_length,
    empty_multirow_row_word,
    encode_rung,
    header_structural_equal,
    normalize_header_entry,
    normalized_header_entries,
    parse_wire_topology,
    synthesize_empty_multirow,
)

from .clipboard import clear_clipboard, copy_to_clipboard, read_from_clipboard

__all__ = [
    "CELL_HORIZONTAL_LEFT_OFFSET",
    "CELL_HORIZONTAL_RIGHT_OFFSET",
    "CELL_VERTICAL_DOWN_OFFSET",
    "CellWireFlags",
    "ClickCodec",
    "Coil",
    "Contact",
    "EMPTY_MULTIROW_MAX_ROWS",
    "EMPTY_MULTIROW_MIN_ROWS",
    "EncodeResult",
    "HeaderSeed",
    "InstructionType",
    "LadderRungV2",
    "RungGrid",
    "V2Degradation",
    "V2EncodeReport",
    "V2UnsupportedShapeError",
    "WireCellTopology",
    "WireTopology",
    "clear_clipboard",
    "copy_to_clipboard",
    "empty_multirow_payload_length",
    "empty_multirow_row_word",
    "encode_rung",
    "header_structural_equal",
    "normalize_header_entry",
    "normalized_header_entries",
    "parse_wire_topology",
    "read_from_clipboard",
    "synthesize_empty_multirow",
]
